services:
  mysql:
    image: mysql:8.0.33
    container_name: mysql
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: wewallads_test
      MYSQL_USER: test
      MYSQL_PASSWORD: 123456
    command:
      --default-time-zone=+08:00
      --bind-address=0.0.0.0
    ports:
      - "33189:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql

networks:
  default:
    name: wewallads-card
